language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
before_script:
  - npm install -g grunt-cli
  - git config --global user.email "test@testy.com"
  - git config --global user.name "Test testy"
  - grunt
